# Numpy Assignment

In [4]:
import numpy as np

arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12]])

print("Shape:", arr.shape)  # (rows, columns)
print("Size:", arr.size)  # Total number of elements
print("Dimension:", arr.ndim)  # Number of dimensions


Shape: (3, 4)
Size: 12
Dimension: 2


In [6]:
import numpy as np

# Define the 2D array
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12]])

# Access the first row (index 0)
first_row = arr[0]

print("First row:", first_row)

First row: [1 2 3 4]


In [8]:
import numpy as np

# Define the 2D array
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12]])

# Access element at third row (index 2) and fourth column (index 3)
element = arr[2, 3]

print("Element at third row and fourth column:", element)


Element at third row and fourth column: 12


In [10]:
import numpy as np

# Define the 2D array
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12]])

# Extract elements where either row index or column index is odd
odd_indexed_elements = arr[1::2, 1::2]  # Selecting odd-indexed rows and columns

print("Odd-indexed elements:\n", odd_indexed_elements)


Odd-indexed elements:
 [[6 8]]


In [12]:
import numpy as np

# Generate a 3x3 matrix with random values between 0 and 1
random_matrix = np.random.rand(3, 3)

print("Random 3x3 Matrix:\n", random_matrix)


Random 3x3 Matrix:
 [[0.67348456 0.43014213 0.10527096]
 [0.50146109 0.42947849 0.31762164]
 [0.53118691 0.37186756 0.2605583 ]]


In [14]:
import numpy as np

# Uniform Distribution (0 to 1)
rand_uniform = np.random.rand(3,3)
print("Uniform Distribution (0-1):\n", rand_uniform)

# Normal Distribution (mean=0, std=1)
rand_normal = np.random.randn(3,3)
print("\nNormal Distribution (mean=0, std=1):\n", rand_normal)


Uniform Distribution (0-1):
 [[0.27298053 0.49681302 0.55000255]
 [0.93643568 0.51869698 0.33325474]
 [0.70940756 0.24339634 0.11627751]]

Normal Distribution (mean=0, std=1):
 [[-0.89091912  0.2599475   1.60729018]
 [-1.26744955 -2.22271216  0.01086546]
 [-0.36676954 -1.00978493 -0.79360153]]


In [16]:
import numpy as np

# Define the 2D array
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12]])

# Increase dimension using np.newaxis (adds an extra axis)
expanded_arr1 = arr[np.newaxis, :, :]  # Adds a new dimension at the beginning

# Increase dimension using np.expand_dims()
expanded_arr2 = np.expand_dims(arr, axis=0)  # Same as above, adds a new axis at position 0

print("Original Shape:", arr.shape)
print("Expanded Shape:", expanded_arr1.shape)  # Output: (1, 3, 4)


Original Shape: (3, 4)
Expanded Shape: (1, 3, 4)


In [18]:
import numpy as np

# Define the 2D array
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8], 
                [9, 10, 11, 12]])

# Using .T (Transpose)
transposed_arr1 = arr.T

# Using np.transpose()
transposed_arr2 = np.transpose(arr)

print("Original Array:\n", arr)
print("\nTransposed Array:\n", transposed_arr1)


Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed Array:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [20]:
import numpy as np

# Define Matrices A and B
A = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])

# 1. Index-wise Multiplication (Element-wise)
elementwise_multiplication = A * B

# 2. Matrix Multiplication (Dot Product)
matrix_multiplication = np.dot(A, B.T)  # B.T transposes B to make the dimensions compatible

# 3. Addition of Both Matrices
matrix_addition = A + B

# 4. Subtraction (A - B)
matrix_subtraction = A - B

# 5. Division of Matrix B by A (Element-wise)
matrix_division = B / A  

# Print Results
print("Element-wise Multiplication:\n", elementwise_multiplication)
print("\nMatrix Multiplication:\n", matrix_multiplication)
print("\nMatrix Addition:\n", matrix_addition)
print("\nMatrix Subtraction:\n", matrix_subtraction)
print("\nElement-wise Division:\n", matrix_division)


Element-wise Multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matrix Multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Matrix Addition:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Matrix Subtraction:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Element-wise Division:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
import numpy as np

# Original 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshaping to 2x3
reshaped_arr = arr.reshape(2, 3)

print("Original Array:\n", arr)
print("\nReshaped Array (2x3):\n", reshaped_arr)


Original Array:
 [1 2 3 4 5 6]

Reshaped Array (2x3):
 [[1 2 3]
 [4 5 6]]
